name: Autograding Tests

on:
  - push
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Test Apartment
      id: apartment_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Apartment Class"
        command: ./gradlew test --tests oop.ApartmentTest
        timeout: 5
        max-score: 1

    - name: Test Vehicle
      id: vehicle_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Vehicle Class"
        command: ./gradlew test --tests oop.VehicleTest
        timeout: 5
        max-score: 1

    - name: Test Truck
      id: truck_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Truck Class"
        command: ./gradlew test --tests oop.TruckTest
        timeout: 5
        max-score: 1

    - name: Test Shape Hierarchy
      id: shape_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: "Shape Hierarchy"
        command: ./gradlew test --tests oop.ShapeTest
        timeout: 5
        max-score: 2
    - name: Debug total score
      run: |
        echo "Individual test results:"
        echo "Apartment: ${{steps.apartment_test.outputs.result}}"
        echo "Vehicle: ${{steps.vehicle_test.outputs.result}}"
        echo "Truck: ${{steps.truck_test.outputs.result}}"
        echo "Shape: ${{steps.shape_test.outputs.result}}"


    - name: Autograding Report
      uses: classroom-resources/autograding-grading-reporter@v1
      env: 
        APARTMENT_TEST_RESULTS: "${{steps.apartment_test.outputs.result}}"
        VEHICLE_TEST_RESULTS: "${{steps.vehicle_test.outputs.result}}"
        TRUCK_TEST_RESULTS: "${{steps.truck_test.outputs.result}}"
        SHAPE_TEST_RESULTS: "${{steps.shape_test.outputs.result}}"
      with:
        runners: apartment_test,vehicle_test,truck_test,shape_test
